spring.application.name=NotificationService
#TODO: localhost
#spring.rabbitmq.host=localhost
spring.rabbitmq.host=192.168.1.14
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
server.port=8081
server.address=0.0.0.0
logging.level.org.springframework=DEBUG
logging.level.com.example=DEBUG
oauth.jwt.secret=WUUUuSubinnnnuhuuuuuuuuuuuAndrijaaaaaaaaaaaaaaYYYYYYYYY
