spring.application.name=reservation_service
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
server.port=8082
oauth.jwt.secret=WUUUuSubinnnnuhuuuuuuuuuuuAndrijaaaaaaaaaaaaaaYYYYYYYYY
spring.rabbitmq.host=192.168.1.14
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest